title: "Mile One Ventures"
email: mile1ventures@gmail.com
timezone: UTC
baseurl: ""
url: "https://www.mileoneventures.co.uk"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'mile-one-ventures'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-284871470

# Authors
authors:
  Chris:
    name: Chris
    display_name: Chris O'Donoghue
    avatar: 'assets/images/sal.jpeg'
    email: mile1ventures@gmail.com
    web: 
    twitter: 
    description: "Small business technolnogy nerd"
  
# Social
social:
  instagram: https://www.instagram.com/mileoneventures/
  facebook:
  twitter: 

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives

